version: '3'
services: 
  redis1: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7001
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7001 
    volumes: 
      - ./data/1:/data 
    restart: always

  redis2: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7002
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7002 
    volumes: 
      - ./data/2:/data 
    restart: always

  redis3: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7003
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7003 
    volumes: 
      - ./data/3:/data 
    restart: always

  redis4: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7004
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7004 
    volumes:
      - ./data/4:/data 
    restart: always

  redis5: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7005
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7005
    volumes: 
      - ./data/5:/data 
    restart: always

  redis6: 
    image: redis:5.0.6 
    build: 
      context: .  
      dockerfile: Dockerfile 
      args: 
        - EXPOSEPORT=7006
    network_mode: "host" 
    environment: 
      - PASSWORD=1111 
      - CLIENTHOST=192.168.0.41 
      - CLIENTPORT=7006 
    volumes: 
      - ./data/6:/data 
    restart: always

